### PR TITLE
Fix toPath imported from unicorn-magic is not exported

### PR DESCRIPTION
**Pull request by boxexchanger**
https://github.com/sindresorhus/globby/issues/260

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is invalid. `default.js` is for any environment and `node.js` is for Node.js. `toPath` only works for Node.js. The config in this package is correct, so the problem is your bundler config.

**Comment by boxexchanger** [comment]
hi i'm using clear nuxt.js  v3 app

**Comment by boxexchanger** [comment]
image

**Comment by TheAlexLichter** [comment]
> This is invalid. `default.js` is for any environment and `node.js` is for Node.js. `toPath` only works for Node.js. The config in this package is correct, so the problem is your bundler config.

But what if you want to build for non-node environments (e.g. cloudflare workers) and still want to use sth. like `globby`? 🤔
Since that change, it is not universally usable anymore.

**Pull request closed without merging**
